In [3]:
import pandas as pd
import numpy as np

dfMath = pd.read_csv("Main Datasets/Maths.csv")
dfPor = pd.read_csv("Main Datasets/Portuguese.csv")

In [4]:
df = pd.concat([dfMath, dfPor])

In [5]:
df1 = pd.DataFrame()
df1["School"] = df["school"].replace(to_replace = ("GP","MS"), value = ("Gabriel Pereira", "Mousinho da Silveira"))
df1["Sex"] = df["sex"].replace(to_replace = ("F","M"), value = ("Female", "Male"))
df1["Age"] = df["age"].replace(to_replace = (21,22), value = ("20+"))
df1["Area Type"] = df["address"].replace(to_replace = ("U","R"), value = ("Urban", "Rural"))
df1["Family Size"] = df["famsize"].replace(to_replace = ("LE3","GT3"), value = ("Less or Equal to 3", "More than 3"))
df1["Parents Cohabitation"] = df["Pstatus"].replace(to_replace = ("T","A"), value = ("Together", "Apart"))
df1["Mother's Education"] = df["Medu"].replace(to_replace = (0,1,2,3,4), value = ("None", "Primary","5th to 9th grade","Secondary","Higher"))
df1["Father's Education"] = df["Fedu"].replace(to_replace = (0,1,2,3,4), value = ("None", "Primary","5th to 9th grade","Secondary","Higher"))
df1["Mother's Job"] = df["Mjob"].replace(to_replace = ("teacher","health","services","at_home"), value = ("Teacher","Health","Services","At Home"))
df1["Fathers's Job"] = df["Fjob"].replace(to_replace = ("teacher","health","services","at_home","other"), value = ("Teacher","Health","Services","At Home","Other"))
df1["Reason"] = df["reason"].replace(to_replace = ("home","reputation","course","other"), value = ("Close to Home","School Reputation","Course Preference","Other"))
df1["Guardian"] = df["guardian"].replace(to_replace = ("father","mother","other"), value = ("Father","Mother","Other"))
df1["Study Time"] = df["studytime"].replace(to_replace = (1,2,3,4), value = ("Less than 2 hours","2 to 5 hours","5 to 10 hours", "More than 10 hours"))
df1["Failed"] = df["failures"]
df1["Extra School Support"] = df["schoolsup"]
df1["Extra Paid Courses"] = df["paid"]
df1["Extra Activities"] = df["activities"]
df1["Attended Nursery School"] = df["nursery"]
df1["Wants Higher Education"] = df["higher"]
df1["Internet Access"] = df["internet"]
df1["In a Romantic Relation"] = df["romantic"]
df1["Family Relation"] = df["famrel"].replace(to_replace = (1,2,3,4,5), value = ("Very Bad","Bad","Normal","Good","Excellent"))
df1["Free Time"] = df["freetime"].replace(to_replace = (1,2,3,4,5), value = ("Very Low","Low","Normal","High","Very High"))
df1["Go Out"] = df["goout"].replace(to_replace = (1,2,3,4,5), value = ("Very Low","Low","Normal","High","Very High"))
df1["Workday Alcohol Consumption"] = df["Dalc"].replace(to_replace = (1,2,3,4,5), value = ("Very Low","Low","Normal","High","Very High"))
df1["Weekly Alcohol Consumption"] = df["Walc"].replace(to_replace = (1,2,3,4,5), value = ("Very Low","Low","Normal","High","Very High"))
df1["Health Status"] = df["health"].replace(to_replace = (1,2,3,4,5), value = ("Very Low","Low","Normal","High","Very High"))
df1["# of Class Absent"] = df["absences"]

In [5]:
df1.to_csv("Merged - Alcohol Effects on Study.csv", index=False)

In [6]:
FamilyInfo = df1[[
    "Family Size",
    "Parents Cohabitation",
    "Mother's Education",
    "Father's Education",
    "Mother's Job",
    "Fathers's Job",
    "Family Relation",
    "Guardian"
]]

FamilyInfo.drop_duplicates( inplace=True, ignore_index = True)
FamilyInfo["FamilyInfoSK"] = range(1, len(FamilyInfo)+1)

FamilyInfo.to_csv("Data Modeled Tables/Family Info.csv", index = False)

C:\Users\hp\AppData\Local\Temp\ipykernel_9432\1917855665.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  FamilyInfo.drop_duplicates( inplace=True, ignore_index = True)
C:\Users\hp\AppData\Local\Temp\ipykernel_9432\1917855665.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  FamilyInfo["FamilyInfoSK"] = range(1, len(FamilyInfo)+1)

In [7]:
StudentInfo = df1[[
    "Extra School Support",
    "Extra Paid Courses",
    "Extra Activities",
    "Attended Nursery School",
    "Wants Higher Education",
    "Internet Access",
    "In a Romantic Relation",
    "Free Time",
    "Go Out"
]]

StudentInfo.drop_duplicates( inplace=True, ignore_index = True)
StudentInfo["StudentInfoSK"] = range(1, len(StudentInfo)+1)

StudentInfo.to_csv("Data Modeled Tables/Student Info.csv", index = False)

C:\Users\hp\AppData\Local\Temp\ipykernel_9432\532601272.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  StudentInfo.drop_duplicates( inplace=True, ignore_index = True)
C:\Users\hp\AppData\Local\Temp\ipykernel_9432\532601272.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  StudentInfo["StudentInfoSK"] = range(1, len(StudentInfo)+1)

In [8]:
df1= df1.merge(FamilyInfo, how = "left", on = [
    "Family Size",
    "Parents Cohabitation",
    "Mother's Education",
    "Father's Education",
    "Mother's Job",
    "Fathers's Job",
    "Family Relation",
    "Guardian"])

df1= df1.merge(StudentInfo, how = "left", on = [
    "Extra School Support",
    "Extra Paid Courses",
    "Extra Activities",
    "Attended Nursery School",
    "Wants Higher Education",
    "Internet Access",
    "In a Romantic Relation",
    "Free Time",
    "Go Out"])

In [9]:
Fact = df1[[
    "School",
    "Sex",
    "Age",
    "Area Type",
    "Reason",
    "Study Time",
    "Failed",
    "Workday Alcohol Consumption",
    "Weekly Alcohol Consumption",
    "Health Status",
    "# of Class Absent",
    "FamilyInfoSK",
    "StudentInfoSK"
]]

Fact.to_csv("Data Modeled Tables/Fact.csv", index = False)

In [10]:
Fact

,School,Sex,Age,Area Type,Reason,Study Time,Failed,Workday Alcohol Consumption,Weekly Alcohol Consumption,Health Status,# of Class Absent,FamilyInfoSK,StudentInfoSK
0,Gabriel Pereira,Female,18,Urban,Course Preference,2 to 5 hours,0,Very Low,Very Low,Normal,6,1,1
1,Gabriel Pereira,Female,17,Urban,Course Preference,2 to 5 hours,0,Very Low,Very Low,Normal,4,2,2
2,Gabriel Pereira,Female,15,Urban,Other,2 to 5 hours,3,Low,Normal,Normal,10,3,3
3,Gabriel Pereira,Female,15,Urban,Close to Home,5 to 10 hours,0,Very Low,Very Low,Very High,2,4,4
4,Gabriel Pereira,Female,16,Urban,Close to Home,2 to 5 hours,0,Very Low,Low,Very High,4,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1039,Mousinho da Silveira,Female,19,Rural,Course Preference,5 to 10 hours,1,Very Low,Low,Very High,4,320,244
1040,Mousinho da Silveira,Female,18,Urban,Course Preference,2 to 5 hours,0,Very Low,Very Low,Very Low,4,321,256
1041,Mousinho da Silveira,Female,18,Urban,Course Preference,2 to 5 hours,0,Very Low,Very Low,Very High,6,322,171
1042,Mousinho da Silveira,Male,17,Urban,Course Preference,Less than 2 hours,0,Normal,High,Low,6,324,197
1043,Mousinho da Silveira,Male,18,Rural,Course Preference,Less than 2 hours,0,Normal,High,Very High,4,78,247