### Importing The Main CSV File

In [38]:
import pandas as pd

df = pd.read_csv("owid-covid-data.csv")

### Droping the Summerized NULL Continental Information

In [46]:
df = df.dropna(subset = "continent")

Empty DataFrame
Columns: [iso_code, continent, location, date, new_cases, new_deaths, reproduction_rate, icu_patients, hosp_patients, new_tests, positive_rate, tests_per_case, tests_units, people_vaccinated, people_fully_vaccinated, total_boosters, new_vaccinations, stringency_index, population, population_density, median_age, aged_65_older, aged_70_older, gdp_per_capita, extreme_poverty, cardiovasc_death_rate, diabetes_prevalence, female_smokers, male_smokers, handwashing_facilities, hospital_beds_per_thousand, life_expectancy, human_development_index, excess_mortality_cumulative_absolute, excess_mortality_cumulative, excess_mortality]
Index: []

[0 rows x 36 columns]

### New dataframe "Location" 

* Creating a new dataframe "Location" from the main dataframe
* Removing duplicates, so we can have all unique rows

In [48]:
Location = df[["iso_code","continent","location"]]
Location.drop_duplicates(inplace = True, ignore_index= True)

Location.to_csv("Covid - Split Tables/Locations.csv",index= False, columns=["iso_code","continent","location"])

C:\Users\hp\AppData\Local\Temp\ipykernel_10168\128449636.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Location.drop_duplicates(inplace = True, ignore_index= True)

### New dataframe "Demographic" 

* Creating a new dataframe "Demographic" from the main dataframe
* Removing duplicates, so we can have all unique rows
* Adding a Index as "ID"

In [49]:
Demographic = df[["population",
"population_density",
"median_age",
"aged_65_older",
"aged_70_older",
"gdp_per_capita",
"extreme_poverty"]]


Demographic.drop_duplicates(inplace = True, ignore_index= True)
Demographic['Demographic ID'] = range(1, len(Demographic) + 1)
Demographic.to_csv("Covid - Split Tables/Demographic.csv",index= False)

C:\Users\hp\AppData\Local\Temp\ipykernel_10168\3081651235.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Demographic.drop_duplicates(inplace = True, ignore_index= True)
C:\Users\hp\AppData\Local\Temp\ipykernel_10168\3081651235.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Demographic['Demographic ID'] = range(1, len(Demographic) + 1)

### New table "Other" 

* Creating a new table "Other" from the main dataframe 
* Removing duplicates, so we can have all unique rows
* Adding a Index as "ID"

In [51]:
Other = df[[
    'stringency_index',
    'cardiovasc_death_rate',
    'diabetes_prevalence',
    'female_smokers',
    'male_smokers',
    'handwashing_facilities',
    'hospital_beds_per_thousand',
    'life_expectancy',
    'human_development_index',
    'excess_mortality_cumulative_absolute',
    'excess_mortality_cumulative',
    'excess_mortality']]

Other.drop_duplicates(inplace = True, ignore_index= True)

Other['Other ID'] = range(1, len(Other) + 1)
Other.to_csv("Covid - Split Tables/Other.csv",index= False)

C:\Users\hp\AppData\Local\Temp\ipykernel_10168\3227241328.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Other.drop_duplicates(inplace = True, ignore_index= True)
C:\Users\hp\AppData\Local\Temp\ipykernel_10168\3227241328.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Other['Other ID'] = range(1, len(Other) + 1)

### Merging Dataframes

* Merging newly created dataframe with main dataframe using left join, So we can have "ID" in main dataframe & later we can remove other columns.
* We will not merge the "Location" dataframe as it has a column "iso_code" which is unique itself, so we'll use the "iso_code" as the "ID" for "Location"

In [52]:
fact = df
fact = fact.merge(Demographic, how = 'left', on = ["population","population_density","median_age","aged_65_older","aged_70_older","gdp_per_capita","extreme_poverty"])
fact = fact.merge(Other, how = 'left', on = ['stringency_index','cardiovasc_death_rate','diabetes_prevalence','female_smokers','male_smokers','handwashing_facilities','hospital_beds_per_thousand','life_expectancy','human_development_index','excess_mortality_cumulative_absolute','excess_mortality_cumulative','excess_mortality'])
fact

,iso_code,continent,location,date,new_cases,new_deaths,reproduction_rate,icu_patients,hosp_patients,new_tests,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,Demographic ID,Other ID
0,AFG,Asia,Afghanistan,2/24/2020,5.0,NaN,NaN,NaN,NaN,NaN,...,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,1,1
1,AFG,Asia,Afghanistan,2/25/2020,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,1,1
2,AFG,Asia,Afghanistan,2/26/2020,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,1,1
3,AFG,Asia,Afghanistan,2/27/2020,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,1,1
4,AFG,Asia,Afghanistan,2/28/2020,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206133,ZWE,Africa,Zimbabwe,9/19/2022,94.0,0.0,1.89,NaN,NaN,NaN,...,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,231,20616
206134,ZWE,Africa,Zimbabwe,9/20/2022,66.0,0.0,NaN,NaN,NaN,NaN,...,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,231,20616
206135,ZWE,Africa,Zimbabwe,9/21/2022,0.0,0.0,NaN,NaN,NaN,NaN,...,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,231,20616
206136,ZWE,Africa,Zimbabwe,9/22/2022,103.0,0.0,NaN,NaN,NaN,NaN,...,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,231,20616
206137,ZWE,Africa,Zimbabwe,9/23/2022,30.0,1.0,NaN,NaN,NaN,NaN,...,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,231,20616

In [57]:
### Exporting the "Fact" dataframe with the desired subsets

In [53]:
fact = fact[['date','Demographic ID', 'iso_code', 'Other ID', 'new_cases','new_deaths','reproduction_rate', "new_tests","positive_rate","tests_per_case","tests_units","people_vaccinated","people_fully_vaccinated","total_boosters","new_vaccinations","icu_patients","hosp_patients"]]
fact.to_csv("Covid - Split Tables/Fact.csv",index= False)